/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AtlasApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "AtlasApiRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "AtlasDb": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "reader": string
      "secretArn": string
      "type": "sst.aws.Aurora"
      "username": string
    }
    "AtlasMigrate": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AtlasSeedAchievements": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AtlasSeedGeo": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AtlasUploads": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "AtlasVpc": {
      "type": "sst.aws.Vpc"
    }
    "AtlasWeb": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "Email": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "EmailDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MaplibreTilesKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ProcessActivity": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ProcessActivityDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "SessionSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StravaClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StravaClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StravaSync": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "StravaSyncDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "WorkerProcessActivity": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}